### ISSUE TITLE
Jwt payload return only ROLE_USER

### ISSUE THREAD

**Issue by oschwartz** [gesdinet/JWTRefreshTokenBundle#149]
Hi,
When i refresh the jwt token the payload return only  "ROLE_USER" instead "ROLE_ADMIN"

**Comment by mmadariaga** [comment]
I fixed this by setting the user provider https://github.com/gesdinet/JWTRefreshTokenBundle/blob/master/README.md#config-userprovider. 

It creates a "basic" token with the username and ROLE_USER otherwise https://github.com/gesdinet/JWTRefreshTokenBundle/blob/master/Security/Provider/RefreshTokenProvider.php#L62
