### ISSUE TITLE
Symfony 3.0 compatibility

### ISSUE THREAD

**Issue by clonitza** [gesdinet/JWTRefreshTokenBundle#24]
Thanks for the hard work you put in this bundle. Do you have any plans to make it compatible with Symfony 3.0 in the near future?

**Comment by markitosgv** [comment]
Thanks @clonitza , yes we need to add 3.0 support. Im going to create a new 3.0 branch to work. PR will be merged in this.

**Comment by clonitza** [comment]
Thanks a lot! Great news mate! :+1:

**Comment by Flo-Schield-Bobby** [comment]
+1, excellent to hear !

Please just keep in mind that JWTAuthenticationBundle currently allows Symfony3 only on the `dev-master` branch (>= 2.0), which is currently not released, but available as a development branch.

In order to allow Symfony3, it would be necessary to update the composer version of this bundle.

**Comment by Flo-Schield-Bobby** [comment]
JWTAuthenticationBundle just released the `1.4.2` tag, compatible with both Symfony2.3 and Symfony3.0.

Hope you will be able to release this branch soon with Symfony3 and JWTAuthenticationBundle 1.4.2 compatibility!

**Comment by markitosgv** [comment]
Hi guys, i have created a new 3.0 branch, we need to fix issues in this to add symfony 3.0 support, i started with composer.json and travis changes
